version: '3'

services:
  faq:
    build: ./Dockerfiles/deep
    container_name: deeppavlov-faq
    image: deeppavlov-faq:latest
    ports:
      - "5000:5000"
    networks:
      - code-network
    restart: always
networks:
  code-network:
    driver: bridge